return {
	{},
	{
		"",
		"Chapter 18",
		"A Beige Colored Bookmark"
	},
	{
		"Beige. A wall. No, the ceiling. Gray transitions to beige right to left on the ceiling above me. Sunlight peeks through the blinds to the left of my bed, casting light upon my squinting eyes. I feel a tear travel across my cheek, then another, and it is in this that I know I am awake.",
		"I've been waking up crying lately, but not out of sadness. It doesn't feel sad.",
		"Abruptly awake, with no sense of whether I was dreaming or not, I'll lie there for some time, regarding the tears with a certain curiosity, but nothing more. Why is my body behaving like this? Is it reacting to something now lost to me? It's as though I suddenly find myself in bed crying with no recollection of how I got there. But it doesn't feel sad. It doesn't feel like anything.",
		"I wipe my cheeks with the heavy quilt covering my body before pulling it off, swing my legs over the edge, left then right, and stand to start my day.",
	},
	{
		"Why do we cry?",
		"Internet searches assist in confirming what I already know. “We cry to shed a bit of ourselves and our grief, often after a loss.” I am neither a biologist nor a poet, but this makes enough sense to me both physiologically and metaphorically.",
		"Why do I wake up crying?",
		"The Internet is less helpful here. “When you wake up crying, it simply means that your soul is still alive and it can be touched.” What is the soul? And how is this simple? It sounds like Freud writing a feel-good self-help book.",
		"What have I lost?",
	},
	{
		"Missing my bus again, I call an Uber. The driver, an older woman named Maria, motions for me to get in the backseat as she pulls up. Initial exchanges with strangers are always awkward for me; my mind is never confident of what to say and where to go, so I'm grateful for her directness here.",
		"“How ‘bout the game last night?” she asks me, attempting to make conversation. “Which game?” I reply, delaying the inevitable. “The Pens. The Pens of course.”",
		"“I'm sorry, I don't really follow sports. What, uh, what sport do the Pens play?” I try to sound as earnestly inquisitive as I can muster. She laughs heartily. “You've gotta be the first person I've ever met around here that doesn't follow hockey.” She chuckles some more, shaking her head with a smile. I feel my mouth form a sheepish half smile. “I'm glad I could at least provide some humor to your day.”",
		"“Well, okay then,” she continues, “you don't like sports. What do you like to do?”",
		"“Well, I go to work, and… come home and read things, and…” My voice trails off.",
		"“Mm,” she nods. “You sound a little lost.”",
		"“Yeah, I guess, maybe.” I have a sense of my mind leaving the tracks in front of it for uncharted rumination. It's too late already, but I try to steer a little longer. “How about you? What do you like to do?”",
		"“Oh, well, I live a quiet life now, mostly just driving like this to make ends meet and keep myself busy. Things were tough when my husband passed three years ago. I barely got out of bed for six months. Hardly ate anything. It was tough. But I couldn't do that forever. Life goes on, you know? The days continue to come.”",
		"When was the last time I felt sadness like that? I think back, trying to recall if I've ever known such sorrow, but everything seems so distant and hazy.",
		"Recollection trickles in, slowly at first. I guess It must have been about five years ago when my psychiatrist died in a car accident. He'd been seeing me for nearly a decade at that point. We'd built up an understanding of one another both across that time, and he was always so kind.",
		"I'd lacked the capacity to appreciate it during the darkest depths of my sickness back then, but he wanted me to get better. He was present for each of my 5:30 am ECT sessions and visited me each morning during my multiple hospitalizations the same year. And he did help me get better, slowly better. Over the final year's appointments with him, I would look around the waiting room, and see others reeling in their own sicknesses and know that I'd been there myself not so long before. When the news came that there was practically nothing left of his body, I wept, not immediately, but over the following weeks and months. Why did he have to die? Why couldn't it have been—",
		"“If I can give you any advice,” she says, pulling the car to a stop and me out of my mind, “it's to treasure your days like your dreams. Both have a way of fading when you wake up.”",
	},
	{
		"While walking home for the evening, I pause to peek into the used bookstore through its storefront glass.  My morning commutes have been increasingly hectic lately, but I can afford to dawdle on the return trip like this.  It seems I've been taking longer and longer to drag myself out of bed in the mornings.  Should I linger much more, I'll probably start missing the last bus I can catch without arriving late to work.",
		"The space on the other side of the window is not wide but runs deep, with mirrored alcoves of bookshelves allotted every fifteen feet or so. I don't think I've ever seen a single customer inside. How does this place remain open? The rent has got to be insane given its location. Despite such misgivings, I associate the space with an inscrutable wistfulness, pleasant times now lost to memory. Should I enter? What do I hope to find within? I cannot say.",
		"My feet carry me in as pedestrians continue to pass by on the sidewalk outside.",
		"The store keeper doesn't acknowledge my entering, only turning the page of the book he's reading, a paperback copy of The Great Gatsby. Four impressively bulky circular wooden tables line the central corridor between the shelves. Each possesses a stately venerability despite its faded lacquer and heavy dust coat.  I approach one and let my fingers trace the various chips and scratches marking the surface. They are scars worn smooth by time; still, one wonders how they got there.  I hear the store keeper turn the page.",
		"The shelving seems to be organized into broad categories by handwritten signage hanging from the ceiling.  The first alcove is labeled as fiction; after that is non-fiction, with science/math further away.  The books on the shelves don't seem to be organized in any fashion I can discern, but perhaps it is just that I don't recognize anything.",
		"Scanning the covers, I take note of Dostoevsky's The Brothers Karamazov slightly to my left; further to the right I find Aeschylus' Agamemnon.  What are the others between and beyond?  How many books are there that I'll never read?  How many stories have been penned out for me to never know the existence of?  The volume of words, of stories, of lives lived now gone–it overwhelms, and I retreat away, back towards the store keeper, the only other living thing here.",
		"“How can I help you?”",
		"I inhale and then hear my voice ask, “Do you ever wake up crying?”",
		"In the moment that follows, I understand that we exist just a few feet apart, only divided by his spectacles, neatly trimmed beard, and paperback book.  His blank eyes, his straight lips, they are outwardly expressionless, yet I feel confident they belie an inner sympathy actively masked to the world.  Does he understand me?",
		"He closes the pages of his book gently on a beige colored bookmark, retaining a link to the world within.  His head shakes almost imperceptibly.  “I'm sorry.  What?”",
		"I shouldn't have asked.  “I… do you have anything by Kafka?”",
		"There is further silence, during which I comprehend the chasm for what it is.  His eyes narrow slightly, analyzing me, piecing together what has just occurred.  He exhales softly.  “Are you looking for something in particular by Kafka?”",
		"“No, I just… His name keeps coming up in other things I read.  I figured I should finally investigate the source material.  I think anything by Kafka should do.”",
		"He nods and lowers his book.  “I recall there being a few copies of The Metamorphosis in the fiction section.  Let's check.”",
	},
	{
		"I'm in your bedroom, sitting with my back to the wall in your bed, half dressed.  A copy of The Buried Giant lies closed on my lap. You are in the kitchen boiling water for tea. We can't see one another, but our conversation floats in and out of audibility, our words passing through the doorframe that separates us. I describe the ending to The Witness, a game I'd recently completed. “Why, though?” you respond incredulously. “Why would you make your audience endure that?”  I hear us both laugh.",
		"“This is it.”  My mouth forms the words but there is no sound.  “This will be the last memory I have of us being happy together.”",
		"My mind has been derailing more frequently and easily of late, and I'm afraid of where it's headed. Hell seems inevitable at this point. “It just sounds stressful,” you continue. Your tone is light and unfettered by the fountain of fear and insecurity welling up in my chest. You don't yet know what's coming. You can't feel it as I do.",
		"More than anything, I just want for you to understand, to know my mind and how it works and why I'm so broken.  I wish I could change how I communicated to you over the years we were together. I wish I could have been more honest with you.  You deserved to know the truth about how I felt so alone in your arms.  How I wanted to rely on you, but still sought out support from others elsewhere on Earth late at night while you slept. How I felt so ungrateful, and unfaithful, and riddled with self-imposed complexity, guilt, and shame. How I was so afraid to tell you that I'd taken to sleeping on the floor of my office some nights to hide from it all.  I was so scared of my body and my mind; I still am. I just wish I could have told you.",
		"“Mmmm,” you murmur contentedly, entering the bedroom carrying a cup and a blithe smile. “Tea.”",
	},
	{
		"Beige. A wall. No, the ceiling. Gray transitions to beige right to left on the ceiling above me. Sunlight peeks through the blinds to the left of my bed, casting light upon my squinting eyes. I feel a tear travel across my cheek, then another, and it is in this that I know I am awake."
	},
}